import {firebaseConfig,appSettings} from "./firebase-config.js";
import {getApps,getApp,initializeApp} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import {getAuth,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import {getFirestore,collection,getDocs,doc,runTransaction,serverTimestamp,onSnapshot,query,where} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const money=(n,c)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})+" "+(c||"HTG");
const toast=t=>{const e=$("#toast");if(!e)return;e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)};
const configured=()=>firebaseConfig.apiKey&&!String(firebaseConfig.apiKey).includes("YOUR_");
if(configured()){
 const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
 let admin=null,users=[],profiles=[],txs=[],off=null;
 function label(uid){const p=profiles.find(x=>x.id===uid)||{},u=users.find(x=>x.id===uid)||{};return p.displayName||p.username||u.phone||uid}
 async function loadUsers(){const [us,ps]=await Promise.all([getDocs(collection(db,"users")),getDocs(collection(db,"publicProfiles"))]);users=us.docs.map(d=>({id:d.id,...d.data()}));profiles=ps.docs.map(d=>({id:d.id,...d.data()}));const opts=users.map(u=>`<option value="${u.id}">${esc(label(u.id))}</option>`).join("");$("#manualUser").innerHTML='<option value="">Chwazi itilizatè...</option>'+opts;$("#ledgerUser").innerHTML='<option value="">Tout itilizatè</option>'+opts;$("#manualCurrency").innerHTML=appSettings.currencies.map(c=>'<option>'+c+'</option>').join("")}
 function render(){const uid=$("#ledgerUser").value,type=$("#ledgerType").value;const rows=txs.filter(x=>(!uid||x.userId===uid)&&(!type||x.type===type)).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));$("#ledgerList").innerHTML=rows.length?rows.map(x=>`<div class="adminRow"><b>${esc(x.type||"transaction")} • ${money(x.amount,x.currency)}</b><br><span class="muted">${esc(label(x.userId))} • ${esc(x.reference||"")} • ${esc(x.note||"")}</span></div>`).join(""):'<p class="muted">Pa gen tranzaksyon.</p>'}
 $("#ledgerUser").onchange=render;$("#ledgerType").onchange=render;
 $("#manualWalletForm").onsubmit=async e=>{e.preventDefault();if(!admin)return;const uid=$("#manualUser").value,type=$("#manualType").value,amount=Number($("#manualAmount").value),currency=$("#manualCurrency").value;if(!uid||!(amount>0))return toast("Verifye itilizatè ak montan.");try{await runTransaction(db,async tx=>{const ur=doc(db,"users",uid),us=await tx.get(ur);if(!us.exists())throw new Error("Itilizatè pa jwenn.");const balances={...(us.data().walletBalances||{})},have=Number(balances[currency]||0);if(type==="withdrawal"&&have<amount)throw new Error("Balans ensifizan.");balances[currency]=type==="deposit"?have+amount:have-amount;tx.update(ur,{walletBalances:balances,updatedAt:serverTimestamp()});tx.set(doc(collection(db,"walletTransactions")),{userId:uid,type,amount,currency,reference:$("#manualReference").value.trim(),note:$("#manualNote").value.trim(),source:"admin_manual",adminId:admin.uid,createdAt:serverTimestamp()});tx.set(doc(collection(db,"notifications")),{recipientId:uid,title:type==="deposit"?"Depo admin":"Retrè admin",message:(type==="deposit"?"+":"-")+money(amount,currency),read:false,createdAt:serverTimestamp()})});e.target.reset();toast("Operasyon anrejistre.")}catch(err){console.error(err);toast(err.message||"Operasyon echwe.")}};
 onAuthStateChanged(auth,async u=>{off?.();if(!u)return;const t=await u.getIdTokenResult(true);if(t.claims.admin!==true)return;admin=u;await loadUsers();off=onSnapshot(collection(db,"walletTransactions"),s=>{txs=s.docs.map(d=>({id:d.id,...d.data()}));render()})});
}
